[tool.poetry]
name = "fabrics"
version = "0.2.0"
description = "Optimization fabrics in python."
authors = ["Max Spahn <m.spahn@tudelft.nl>"]

[tool.poetry.dependencies]
python = "^3.7,<3.11"
pytest = "^6.2.5"
casadi = "^3.5.1"
numpy = "^1.5.1"
geomdl = "^5.3.1"
motion_planning_scenes = "^0.1"
gym = { version = "^0.21.0", optional = true}
scipy = {version = "^1.7.3", optional = true}
matplotlib = {version = "^3.5.1", optional = true}
forwardkinematics = "^0.5.0"
planarenvs = {git = "https://git@github.com/maxspahn/gym_envs_planar.git", rev = "ft-clean-build", optional = true}

[tool.poetry.dev-dependencies]

[tool.poetry.extras]
agents = ["gym", "planarenvs"]
tutorials = ["scipy", "matplotlib"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
