[tool.poetry]
name = "fabrics"
version = "0.1.0"
description = "Optimization fabrics in python."
authors = ["Max Spahn <m.spahn@tudelft.nl>"]

[tool.poetry.dependencies]
python = "^3.7,<3.11"
pytest = "^6.2.5"
casadi = "^3.5.1"
numpy = "^1.5.1"
geomdl = "^5.3.1"
forwardkinematics = "^0.4"
gym = { version = "^0.21.0", optional = true}
motion_planning_scenes = {version = "^0.1", optional = true}
scipy = {version = "^1.7.3", optional = true}
matplotlib = {version = "^3.5.1", optional = true}

[tool.poetry.dev-dependencies]

[tool.poetry.extras]
agents = ["gym", "motion_planning_scenes"]
tutorials = ["scipy", "matplotlib"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
