[tool.poetry]
name = "fabrics"
version = "0.5.0"
description = "Optimization fabrics in python."
authors = ["Max Spahn <m.spahn@tudelft.nl>"]

[tool.poetry.dependencies]
python = "^3.8,<3.10"
casadi = "^3.5.4,!=3.5.5.post1,!=3.5.5.post1"
numpy = "^1.15.3"
geomdl = "^5.3.1"
pyquaternion = "^0.9.9"
pickle-mixin = "^1.0.2"
quaternionic = "^1.0.0"
forwardkinematics = "^1.0"
mpscenes = "^0.1"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pylint = "^2.13.4"
pytest = "^6.2.5"
pytest-cov = "^4.0.0"

[tool.poetry.group.tutorials]
optional = true

[tool.poetry.group.tutorials.dependencies]
scipy = "^1.5.1"
matplotlib = "^3.3.1"

[tool.poetry.group.agents]
optional = true

[tool.poetry.group.agents.dependencies]
urdfenvs = "^0.5.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
