# This is a basic workflow to help you get started with Actions

name: Build and Agents

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install custom packages
      - name: Install fabricsPackage
        run: pip install -e fabrics_package

      # Runs a set of commands using the runners shell
      - name: Test testAgents
        run: python tests/agents/simpleAgentTest.py

      - name: Test examples
        run: python gym_agents/running/panda/pandaAgent.py 10
